### ISSUE TITLE
Prototype release

### ISSUE THREAD

**Issue by monasobh** [fontvu/BTU-WebDocs-WS22#14]
Hello, we just wanted to let you know that we will be done with our first prototype next monday (9.1) and are looking forward to your feedback.

**Comment by vincenzodonn** [comment]
HTML files are uploaded. You can check the pages on the branch and github pages. If there is anything missing such as content or images it's because it was not found in your content folder. 

So either provide us with the content and the right images or we can use the same content and images for them.

We are waiting for your feedback on HTML prototype release.

Thanks.

**Comment by venttis-1** [comment]
Text for "Security analysis and architectural advice"

Our Security Analysis and Architectural Advice service is designed to provide comprehensive, tailored security solutions for your cybersecurity needs. With our experienced team of experts, we can provide you with an in-depth analysis of your current security setup and offer advice on how to improve it. We can also provide architectural advice on how to best design and implement your security architecture for maximum effectiveness. Our service is tailored to fit your needs and budget, so you can rest assured that you're getting the best possible protection from the latest threats. With our help, you can be sure that your data and systems are safe and secure. Especially for young and quickly developing projects, an early security analysis, design help and architectural advice help more than a penetration test close to the launch date. We can help finding out if a chosen resource is secure enough  and trustworthy.
